Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MolaaApp.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MolaaApp.Data.Abstract;
using MolaaApp.Models;
using Microsoft.EntityFrameworkCore;
using MolaaApp.Data.Concrete;

namespace MolaaApp.Controllers
{
    public class PostsController:Controller
    {
        // private readonly BlogContext _context;//BlogContext ten nesne ürettim
        // //veri tabanı bilgilerini çekmek için
        // public PostsController(BlogContext context){
        //     _context = context;
        // }bu injection yöntemi bunun yerine interface aracılığı ile yapıp bağımlılıkları ortadan kaldırıp ayrıca yazdığım kodları tek bir yerden kontrol etmiş oldum

        //**Postun içinde tag bilgileri olduğu için onuda ekledim
        //ancak iki tablodan veri göndereceğim için bunları ortak bir models(PostsViewModel) içinde çağırıp index sayfasına ekleyerek yaptım

        //bu yöntemden sonra ben component kullanarak veri çektim onun için bu bilgileri sidim
        private UserManager<AppUser> _userManager;//usertablosundaki verileri veritabnından getirdim
        private IPostRepository _postRepository;

        private ICommentRepository _commentRepository;

        private ILikeRepository _likeRepository;

        public PostsController(IPostRepository postRepository,UserManager<AppUser> userManager,ICommentRepository commentRepository,ILikeRepository likeRepository){
            _postRepository = postRepository;
            _userManager = userManager;
            _commentRepository = commentRepository;
            _likeRepository = likeRepository;
            
        }
        public async Task<IActionResult> Index()
        {
            var posts = _postRepository.Posts.Where(i => i.IsActive);//Isactive ekleyerek sadece true olanları göster dedim
            // IQueryable bir bilgi yani veri tabanından bilgileri şuan almıyorum sadece bağlantıyı sağladım

            return View(new PostsViewModel
            {// index.cshtml sayfasına bilgileri gönderdim
                Posts = await posts.ToListAsync()//burda diyorum ki ya bütün bilgileri gönder ya da if ile koşul sağlanırsa ordaki istediğim bilgileri sadece bana gönder

            }); 
        }



        [Authorize] // kullanıvı giriş yapmadan post ekleme yapmasını engellemek için bunu ekledim
        public IActionResult Create(){
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(PostCreateViewModel model, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); 

                var extension = Path.GetExtension(imageFile.FileName);//dosyanın uzantısını alır ; mesela burda imageFile.FileName buna bakar abc.jpg ise "jpg" kısmını alır
                var randomFileName = string.Format($"{Guid.NewGuid().ToString()}{extension}");//burda random isim oluşturup(Guid.NewGuid()) üste dosyadan aldığım uzatıyı ekliyorum direk
                var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/img", randomFileName);

                //resim eklenmesinde sorun olmazsa burda stremi oluşturuyorum çünkü kapsamdan çıktığında bellekten silinsin diye
                using(var stream = new FileStream(path, FileMode.Create)){
                await imageFile.CopyToAsync(stream);//ilgili dizine kopyaladım resmi ve çalışması için Task<IActionResult> yaptım
                }
                model.Image = randomFileName;

                _postRepository.CreatePost(
                    new Post{
                        Title = model.Title,
                        Content = model.Content,
                        Description = model.Description,
                        Url = model.Url,
                        UserId = userId ?? "",
                        PubilshedOn = DateTime.Now,
                        Image = model.Image,
                        IsActive = false 
                    }
                );
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //önceden url de id bilgisi vardı ben bunu url ile değiştirdim
        public async Task<IActionResult> Details(string url){
            return View(await _postRepository
            .Posts
            .Include(x => x.User)//postu yayınlayan kişinin bilgisini almak için ekledim
            //doğrudan ulaştıklarım include olur ama theninclude farklı bir yere geçip ordaki bilgiyi almak istediğimde öyle yaparım
            .Include(x => x.Comments)//o postla ilgili yorumları ekledim join ile
            .ThenInclude(x => x.User)//bunu böyle yapmamın nedeni commentinde user bilgisini alıp onun içindeki resmi çekmek için
            .FirstOrDefaultAsync(p => p.Url == url));
        }

        [HttpPost]
        public JsonResult AddComment(int PostId, string Text){
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var user = _userManager.Users.FirstOrDefault(u => u.Id == userId);
        var fullName = user != null ? user.FullName : string.Empty;
        var avatarImg = user != null ? user.Image : string.Empty;

        var entity = new Comment{
            PostId = PostId,
            Text = Text,
            PublishedOn = DateTime.Now,
            UserId = userId ?? ""
        };
        _commentRepository.CreateComment(entity);
    
        return Json(new{
            fullName, // username yerine fullName'i döndür
            Text,
            entity.PublishedOn,
            avatarImg
        });
        }   

        [HttpGet]
        public JsonResult GetLikeCount(int postId)
        {
            var likeCount = _likeRepository.likes.Count(l => l.PostId == postId);
            var likedUsers = _likeRepository.likes
                                    .Where(l => l.PostId == postId)
                                    .Select(l => l.User.FullName)
                                    .ToList();

            return Json(new { likeCount, likedUsers });
        }



        [HttpPost]
        public JsonResult AddLike(int postId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var existingLike = _likeRepository.likes.FirstOrDefault(l => l.UserId == userId && l.PostId == postId);


            if (existingLike != null)
            {
                // Kullanıcı daha önce bu gönderiyi beğenmişse like'ı kaldır
                _likeRepository.RemoveLike(existingLike);
                return Json(new { liked = false, likedUsers = _likeRepository.likes.Where(l => l.PostId == postId).Select(l => l.User.FullName).ToList() });
            }
            else
            {
                // Kullanıcı daha önce bu gönderiyi beğenmemişse like'ı ekleyerek işlemi gerçekleştir
                _likeRepository.AddLike(new Like { UserId = userId ?? "", PostId = postId });
                return Json(new { liked = true, likedUsers = _likeRepository.likes.Where(l => l.PostId == postId).Select(l => l.User.FullName).ToList() });
            }
        }

        [HttpGet]
        public JsonResult CheckUserLike(int postId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var existingLike = _likeRepository.likes.FirstOrDefault(l => l.UserId == userId && l.PostId == postId);
        
            return Json(new { liked = existingLike != null });
        }


        [Authorize]
        public async Task<IActionResult> List(){
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var role = User.FindFirstValue(ClaimTypes.Role);
        
            var posts = await _postRepository.Posts.Include(p => p.User).ToListAsync(); // Burada Include metodunu ekledik
        
            if (string.IsNullOrEmpty(role))
            {
                posts = posts.Where(i => i.UserId == userId).ToList(); // Burada Where metodunu çağırdık
            }
            return View(posts);
        }


        [Authorize] // kullanıcı giriş yapmadan post ekleme yapmasını engellemek için bunu ekledim
        public IActionResult Edit(int? id){
            if (id == null)
            {
                return NotFound();
            }

            var post = _postRepository.Posts.FirstOrDefault(i => i.PostId == id);//sayfa yüklenirken kullanıcın önceden seçtiği tagler varsa onlarda gelsin diye
            if (post == null)
            {
                return NotFound();
            }


            return View(new PostCreateViewModel {
                PostId = post.PostId,
                Title = post.Title,
                Description = post.Description,
                Content = post.Content,
                Url = post.Url,
                Image = post.Image,
                IsActive = post.IsActive,
                
            });
        }

        

        [Authorize] // kullanıcı giriş yapmadan post ekleme yapmasını engellemek için bunu ekledim
        [HttpPost]
        public async Task<IActionResult> Edit(PostCreateViewModel model, IFormFile? imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null)
                {
                    var extension = Path.GetExtension(imageFile.FileName);
                    var randomFileName = string.Format($"{Guid.NewGuid().ToString()}{extension}");
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", randomFileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(stream);
                    }
                    model.Image = randomFileName;
                }

                var entityToUpdate = new Post
                {

Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MolaaApp.Models;

namespace MolaaApp.Controllers
{
    [Authorize(Roles ="admin")]
    public class RolesController:Controller
    {
        private readonly RoleManager<AppRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public RolesController(RoleManager<AppRole> roleManager,UserManager<AppUser> userManager){
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index(){
            return View(_roleManager.Roles);//_roleManager.Roles =>IQueryable bir nesnedir yani ben bunu filtreleyip veri tabanına sorgu yazıp istediğim şekilde çekebilirim
        }

        public IActionResult Create(){
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(AppRole model){

            if (ModelState.IsValid)
            {
                var result = await _roleManager.CreateAsync(model);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError("",err.Description);
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Edit(string id){
            var role = await _roleManager.FindByIdAsync(id);//id ile eşleşen role bilgisini aldım

            if (role != null && role.Name != null)
            {
                ViewBag.Users = await _userManager.GetUsersInRoleAsync(role.Name);//Viewbag ile userları aldım ve userslardan o user rolune ait kayıtları getirdim
                return View(role);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AppRole model){
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(model.Id);//modelin içindeki id ile eşleşen role bilgisini aldım

                if (role !=null)
                {
                    role.Name = model.Name;

                    var result =await _roleManager.UpdateAsync(role);//burda ben role ismini güncelledim

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }

                    foreach (var err in result.Errors)
                    {
                        ModelState.AddModelError("",err.Description);
                    }

                    if(role.Name != null){
                        ViewBag.Users = await _userManager.GetUsersInRoleAsync(role.Name);//Viewbag ile userları aldım ve userslardan o user rolune ait kayıtları getirdim
                    }
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id){
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError("", err.Description);
                }
            }
            return RedirectToAction("Index");
        } 
    }
}

Views/Shared/_Layout.cshtml
@if(TempData["message"] != null){<!--hata mesajını herhangi bir sayfada kullanmak istersem diye burda tasarımını yaptım-->
    <div class="alert alert-warning">
        @TempData["message"]
    </div>
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MolaaApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MolaaApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container">
                <!-- Logo ve marka -->
                <a class="navbar-brand" asp-area="" asp-controller="Posts" asp-action="Index">MolaaApp</a>
                <!-- Toggle butonu -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Menü öğeleri -->
                <div class="navbar-nav ms-auto" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        @if(User.IsInRole("admin")){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        }
                        @if(User.Identity?.IsAuthenticated == true){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Posts" asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="meetings" asp-action="Index">Meetings</a>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Merhaba, @User.Identity.Name
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="/meetings/list">My Meetings</a></li>
                                <li><a class="dropdown-item" href="/posts/list">My Posts</a></li>
                                <li><a class="dropdown-item" href="/profile/@User.Identity.Name">My Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a></li>
                            </ul>
                        </li>
                        } else {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; MolaaApp - 2024 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>